name: GH pages update for CFPDB
run-name: ${{ github.actor }} is updating GH pages for CFPDB
on:
  push:
    branches:
      - 'conferences'
  schedule:
    - cron: '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update_GH_pages_for_CFPDB:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run update script
        run: python3 update_cfpdb_on_github.py
        env:
          work_dir: cfpdb_repo
          repo_url: https://github.com/${{ github.repository }}.git
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
